In [13]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

#data00csv.txtの最後の３列がmG（ミリガウス）単位の地磁気データx、y、zとなっている
#data=np.loadtxt('magcal03.txt')#, delimiter=',')
data=np.loadtxt('magcallog02.txt')#, delimiter=',')

#地磁気データ抽出
magx= data[:,1]
magy= data[:,2]
magz= data[:,3]
#magx= data[:,0]
#magy= data[:,1]
#magz= data[:,2]

#最小二乗法
#正規方程式の作成
#1 x2
_x4=sum(magx**4)
_x2y2 =sum(magx**2*magy**2)
_x2z2 =sum(magx**2*magz**2)
_2x3y =sum(2*magx**3*magy)
_2x2yz=sum(2*magx**2*magy*magz)
_2x3z =sum(2*magx**3*magz)
_x3   =sum(magx**3)
_x2y  =sum(magx**2*magy)
_x2z  =sum(magx**2*magz)
#2 y2
_y4   =sum(magy**4)
_y2z2 =sum(magy**2*magz**2)
_2xy3 =sum(2*magx*magy**3)
_2y3z=sum(2*magy**3*magz)
_2xy2z=sum(2*magx*magy**2*magz)
_xy2  =sum(magx*magy**2)
_y3   =sum(magy**3)
_y2z  =sum(magy**2*magz)
#3 z2
_z4   =sum(magz**4)
_2xyz2=sum(2*magx*magy*magz**2)
_2yz3=sum(2*magy*magz**3)
_2xz3 =sum(2*magx*magz**3)
_xz2  =sum(magx*magz**2)
_yz2  =sum(magy*magz**2)
_z3   =sum(magz**3)
#4 xy
_2x2y2=sum(2*magx**2*magy**2)
_2xy2z=sum(2*magx*magy**2*magz)
_2x2yz=sum(2*magx**2*magy*magz)
_x2y  =sum(magx**2*magy)
_xy2  =sum(magx*magy**2)
_xyz  =sum(magx*magy*magz)
#5 yz
_2y2z2=sum(2*magy**2*magz**2)
_2xyz2=sum(2*magx*magy*magz**2)
_xyz  =sum(magx*magy*magz)
_y2z  =sum(magy**2*magz)
_yz2  =sum(magy*magz**2)
#6 xz
_2x2z2=sum(2*magx**2*magz**2)
_x2z  =sum(magx**2*magz)
_xyz  =sum(magx*magy*magz)
_xz2  =sum(magx*magz**2)
#7 x
_x2   =sum(magx**2)
_xy   =sum(magx*magy)
_xz   =sum(magx*magz)
#8 y
_y2   =sum(magy**2)
_yz   =sum(magy*magz)
#9 z
_z2   =sum(magz**2)
#b
_x=sum(magx)
_y=sum(magy)
_z=sum(magz)

#正規行列
M=np.matrix([[     _x4,    _x2y2,    _x2z2,    _2x3y,   _2x2yz,  _2x3z,  _x3, _x2y, _x2z],
             [   _x2y2,      _y4,    _y2z2,    _2xy3,    _2y3z, _2xy2z, _xy2,  _y3, _y2z],
             [   _x2z2,    _y2z2,      _z4,   _2xyz2,    _2yz3,  _2xz3, _xz2, _yz2,  _z3],
             [ _2x3y/2,  _2xy3/2, _2xyz2/2,   _2x2y2,   _2xy2z, _2x2yz, _x2y, _xy2, _xyz],
             [_2x2yz/2,  _2y3z/2,  _2yz3/2, _2xy2z/2,   _2y2z2, _2xyz2, _xyz, _y2z, _yz2],
             [ _2x3z/2, _2xy2z/2,  _2xz3/2, _2x2yz/2, _2xyz2/2, _2x2z2, _x2z, _xyz, _xz2],
             [     _x3,     _xy2,     _xz2,     _x2y,     _xyz,   _x2z,  _x2,  _xy,  _xz],
             [    _x2y,      _y3,     _yz2,     _xy2,     _y2z,   _xyz,  _xy,  _y2,  _yz],
             [    _x2z,     _y2z,      _z3,     _xyz,     _yz2,   _xz2,  _xz,  _yz,  _z2]
            ])

b=np.matrix([_x2, _y2, _z2, _xy, _yz, _xz, _x, _y, _z]).T

#楕円体パラメータの算出
x=np.linalg.inv(M)*(-b)

print('楕円体パラメータ')
print(x)

a11=x[0,0]
a22=x[1,0]
a33=x[2,0]
a12=x[3,0]
a23=x[4,0]
a13=x[5,0]
b1 =x[6,0]
b2 =x[7,0]
b3 =x[8,0]

#楕円体2次項パラメータ行列
A=np.matrix([[a11,a12,a13],[a12,a22,a23],[a13,a23,a33]])

#2次項パラメータ行列の固有値と固有ベクトルを求める
lbda,v=np.linalg.eig(A)

print('固有値・固有ベクトル')
print(lbda)
print(v)

#回転・並行移動
#固有値と基底ベクトル（固有ベクトル）の並べ替え
ax_x=0
ax_y=1
ax_z=2

vt= v.T
vx= vt[ax_x].T
vy= -vt[ax_y].T
vz= vt[ax_z].T
lbdx=lbda[ax_x]
lbdy=lbda[ax_y]
lbdz=lbda[ax_z]


#1次項のパラメータベクトル
B=np.matrix([b1,b2,b3])

#bx=B0[0,ax_x]
#by=B0[0,ax_y]
#bz=B0[0,ax_z]
#B=np.matrix([bx, by, bz])

#対角化行列(回転行列)
P=np.hstack([vx,vy,vz])
print('回転行列')
print(P.T)

#楕円体の中心座標算出
x0=(-B*vx/2/lbdx)[0,0]
y0=(-B*vy/2/lbdy)[0,0]
z0=(-B*vz/2/lbdz)[0,0]

print('中心座標')
print(x0,y0,z0)

O1=np.array([[x0],[y0],[z0]])
O0=P*O1
O0x=O0[0,0]
O0y=O0[1,0]
O0z=O0[2,0]

#球に変換
W=(B*vx)[0,0]**2/4/lbdx + (B*vy)[0,0]**2/4/lbdy + (B*vz)[0,0]**2/4/lbdz -1 
print('W')
print(W)

rx=np.sqrt(W/lbdx)
ry=np.sqrt(W/lbdy)
rz=np.sqrt(W/lbdz)

#print("半径")
#print(rx, ry ,rz)

sx0=np.sqrt(lbdx/W)
sy0=np.sqrt(lbdy/W)
sz0=np.sqrt(lbdz/W)
smax=max(sx0,sy0,sz0)

sx=sx0/smax
sy=sy0/smax
sz=sz0/smax

print('拡大係数')
print(sx0, sy0, sz0)
#print(smax)
#print(1/sx0, 1/sy0, 1/sz0)
#print(sx, sy, sz)


#移動計算のためデータ整形
mag2=np.vstack([magx,magy,magz])

#回転
mag2=P.T*mag2

#並行移動
magx2=np.array(mag2)[0]-x0
magy2=np.array(mag2)[1]-y0
magz2=np.array(mag2)[2]-z0

#拡大縮小
magx2=sx0*magx2
magy2=sy0*magy2
magz2=sz0*magz2

#逆回転
mag3=np.vstack([magx2,magy2,magz2])
mag3=P*mag3
magx3=np.array(mag3)[0]
magy3=np.array(mag3)[1]
magz3=np.array(mag3)[2]


#データのプロット
# グラフの枠を作成
fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

# X,Y,Z軸にラベルを設定
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
#ax.set_xlim([-1200,1200])
#ax.set_ylim([-1200,1200])
#ax.set_zlim([-1200,1200])
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-1.1,1.1])
ax.set_zlim([-1.1,1.1])

ax.set_box_aspect((1,1,1))

# 生データ描画
ax.plot(magx,magy,magz,marker=".",ms=0.1, linestyle='None')

#回転・平行移動後の描画
ax.plot(magx2,magy2,magz2,marker=".",ms=0.1, linestyle='None')

#球を逆回転後の描画
ax.plot(magx3,magy3,magz3,marker=".",ms=0.5, linestyle='None')


#規定ベクトルの描画
ax.plot([0+O0x,vx[0,0]*200+O0x],[0+O0y, vx[1,0]*200+O0y],[0+O0z,vx[2,0]*200+O0z], marker='*', c='r')
ax.plot([0+O0x,vy[0,0]*200+O0x],[0+O0y, vy[1,0]*200+O0y],[0+O0z,vy[2,0]*200+O0z], marker='+', c='g')
ax.plot([0+O0x,vz[0,0]*200+O0x],[0+O0y, vz[1,0]*200+O0y],[0+O0z,vz[2,0]*200+O0z], marker='o', c='b')

#xyz軸描画
ax.plot([-500,500],[0,0],[0,0],c='r')
ax.plot([0,0],[-400,600],[0,0],c='g')
ax.plot([0,0],[0,0],[-400,600],c='b')
#ax.plot([-1.1,1.1],[0,0],[0,0])
#ax.plot([0,0],[-1.1,1.1],[0,0])
#ax.plot([0,0],[0,0],[-1.1,1.1])



# グラフ表示
plt.show()

楕円体パラメータ
[[ 2.40029583e-06]
 [ 2.47452103e-06]
 [ 2.61738934e-06]
 [-1.56643777e-07]
 [-1.80727136e-09]
 [-4.67022323e-09]
 [-3.90785305e-04]
 [-2.17884730e-04]
 [-3.99856449e-03]]
固有値・固有ベクトル
[2.27636113e-06 2.59827457e-06 2.61757050e-06]
[[-0.78435472 -0.61753358 -0.05865107]
 [-0.62015392  0.78277935  0.05162955]
 [-0.01402787 -0.07686857  0.99694255]]
回転行列
[[-0.78435472 -0.62015392 -0.01402787]
 [ 0.61753358 -0.78277935  0.07686857]
 [-0.05865107  0.05162955  0.99694255]]
中心座標
-109.32529343620176 72.76584808916506 759.2285249891385
W
0.5498054412471614
拡大係数
0.002034773458122364 0.002173892202021849 0.0021819494099235273


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
O0z

In [ ]:
plt.close()

In [ ]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

#data00csv.txtの最後の３列がmG（ミリガウス）単位の地磁気データx、y、zとなっている
#機体に乗せていない状態で取得
data1=np.loadtxt('magcal03.txt')#, delimiter=',')
#機体に乗せて取得
data2=np.loadtxt('magcal00.txt', delimiter=',')

#地磁気データ抽出
magx1= data1[:,7]
magy1= data1[:,8]
magz1= data1[:,9]
magx2= data2[:,7]
magy2= data2[:,8]
magz2= data2[:,9]

#データのプロット
# グラフの枠を作成
fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

# X,Y,Z軸にラベルを設定
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
ax.set_xlim([-500,500])
ax.set_ylim([-400,600])
ax.set_zlim([-600,400])
#ax.set_xlim([-1.1,1.1])
#ax.set_ylim([-1.1,1.1])
#ax.set_zlim([-1.1,1.1])

ax.set_box_aspect((1,1,1))

# 生データ描画
ax.plot(magx1,magy1,magz1,marker=".",ms=0.1, linestyle='None')
ax.plot(magx2,magy2,magz2,marker=".",ms=0.1, linestyle='None')

#xyz軸描画
ax.plot([-500,500],[0,0],[0,0],c='r')
ax.plot([0,0],[-400,600],[0,0],c='g')
ax.plot([0,0],[0,0],[-400,600],c='b')
#ax.plot([-1.1,1.1],[0,0],[0,0])
#ax.plot([0,0],[-1.1,1.1],[0,0])
#ax.plot([0,0],[0,0],[-1.1,1.1])



# グラフ表示
plt.show()